import { expect, it } from 'vitest';
import { LibSQLStore } from '@mastra/libsql';
import { Agent } from '@mastra/core/agent';
import { PrivateChannelState, telegramChannels, WEBHOOK_PATH } from '../src/mastra/telegram';
import { readConfig } from '../src/config/env';

it('discards SDK message history before it can enter its cache', async () => {
  const store = new LibSQLStore({ id: 'privacy-test', url: ':memory:' });
  try {
    const state = new PrivateChannelState(store.stores.memory!);
    await state.appendToList('msg-history:telegram:123', { text: 'sensitive example' });
    expect(await state.getList('msg-history:telegram:123')).toEqual([]);
    await state.appendToList('non-message-list', { status: 'ok' });
    expect(await state.getList('non-message-list')).toEqual([{ status: 'ok' }]);
  } finally { await store.close(); }
});

it('uses the webhook path actually generated by the installed Mastra version', async () => {
  const store = new LibSQLStore({ id: 'route-test', url: ':memory:' });
  try {
    const config = readConfig({ TELEGRAM_BOT_TOKEN: '123456:synthetic-test-token', TELEGRAM_BOT_USERNAME: 'fixture_bot', TELEGRAM_WEBHOOK_SECRET_TOKEN: 'a'.repeat(32) });
    const agent = new Agent({
      id: 'financial-blindspot', name: 'Route fixture', instructions: 'Route verification only.',
      model: () => { throw new Error('No inference in route verification'); },
      channels: telegramChannels(config, new PrivateChannelState(store.stores.memory!), async () => { throw new Error('No turn processing in route verification'); }),
    });
    const routes = agent.getChannels()?.getWebhookRoutes();
    expect(routes?.some(route => route.method === 'POST' && route.path === WEBHOOK_PATH)).toBe(true);
  } finally { await store.close(); }
});
