import type { Answers, FieldId } from './schema.js';
import { CURRENCIES, PENSION_TYPES, TOPICS, YES_NO_DK } from './schema.js';

export type Section = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H';
export type FieldType =
  | 'money'
  | 'integer'
  | 'percent'
  | 'year'
  | 'country'
  | 'country_list'
  | 'enum'
  | 'multi_select'
  | 'currency';

export interface FieldDef {
  id: FieldId;
  section: Section;
  prompt: string;
  helper?: string;
  rationale: string;
  type: FieldType;
  options?: string[];
  zeroValid?: boolean;
  allowUnknown: boolean;
  showIf?: (a: Partial<Answers>) => boolean;
  repeat?: 'pensions';
}

export const PENSION_FIELDS: FieldDef[] = [
  {
    id: 'pension_country',
    section: 'D',
    prompt: 'Which country is this pension in?',
    rationale: 'Feeds rule 10 on pensions spread across countries.',
    type: 'country',
    allowUnknown: false,
    repeat: 'pensions',
  },
  {
    id: 'pension_type',
    section: 'D',
    prompt: 'What type is it?',
    rationale: 'Gives context on how this pension pays out.',
    type: 'enum',
    options: [...PENSION_TYPES],
    allowUnknown: false,
    repeat: 'pensions',
  },
  {
    id: 'pension_value',
    section: 'D',
    prompt: 'If it has a pot value, roughly what is it worth today?',
    rationale: 'Feeds the retirement calculation and rule 8 on pensions you cannot see.',
    type: 'money',
    allowUnknown: true,
    repeat: 'pensions',
  },
  {
    id: 'pension_fixed_income_monthly',
    section: 'D',
    prompt: 'If it pays a guaranteed income, roughly how much a month in today\'s money?',
    rationale: 'Feeds the retirement calculation.',
    type: 'money',
    allowUnknown: true,
    repeat: 'pensions',
  },
  {
    id: 'pension_start_age',
    section: 'D',
    prompt: 'At what age does it start paying?',
    rationale: 'Feeds the retirement calculation and rule 9 on pensions starting after you stop.',
    type: 'integer',
    allowUnknown: true,
    repeat: 'pensions',
  },
  {
    id: 'pension_contribution_monthly',
    section: 'D',
    prompt: 'How much goes in each month, including your employer\'s share?',
    rationale: 'Feeds the retirement calculation.',
    type: 'money',
    zeroValid: true,
    allowUnknown: true,
    repeat: 'pensions',
  },
  {
    id: 'pension_contributions_continue',
    section: 'D',
    prompt: 'Will those contributions continue until you retire?',
    rationale: 'Feeds the retirement calculation.',
    type: 'enum',
    options: [...YES_NO_DK],
    allowUnknown: true,
    repeat: 'pensions',
  },
];

export const FIELDS: FieldDef[] = [
  {
    id: 'consent',
    section: 'A',
    prompt: 'I understand this is an educational assessment, not financial advice.',
    rationale: 'Required to continue with the assessment.',
    type: 'enum',
    options: ['yes'],
    allowUnknown: false,
  },
  {
    id: 'age',
    section: 'A',
    prompt: 'How old are you?',
    rationale: 'Feeds the retirement calculation.',
    type: 'integer',
    allowUnknown: false,
  },
  {
    id: 'has_partner',
    section: 'A',
    prompt: 'Are you planning just for yourself, or as a household with a partner?',
    rationale: 'Feeds rule 18 on only one of you knowing where everything is.',
    type: 'enum',
    options: ['just_me', 'household'],
    allowUnknown: false,
  },
  {
    id: 'residence_country',
    section: 'A',
    prompt: 'Which country do you live in?',
    rationale: 'Feeds rule 6 on succession arrangements.',
    type: 'country',
    allowUnknown: false,
  },
  {
    id: 'stay_abroad',
    section: 'A',
    prompt: 'Do you expect to keep living outside your home country long term?',
    rationale: 'Gives context on how settled your situation is.',
    type: 'enum',
    options: ['yes', 'no', 'unsure', 'n/a'],
    allowUnknown: false,
  },
  {
    id: 'dependants',
    section: 'A',
    prompt: 'How many people depend on you financially?',
    rationale: 'Feeds rules 3 and 7 on cover and education costs.',
    type: 'integer',
    zeroValid: true,
    allowUnknown: false,
  },
  {
    id: 'education_funded',
    section: 'A',
    prompt: 'Do you feel you have enough set aside for their education?',
    rationale: 'Feeds rule 7 on education costs that are not funded.',
    type: 'enum',
    options: [...YES_NO_DK],
    allowUnknown: true,
    showIf: (a) => (a.dependants ?? 0) > 0,
  },
  {
    id: 'decision_maker',
    section: 'A',
    prompt: 'Who mainly makes the financial decisions in your household?',
    rationale: 'Feeds rule 18 on only one of you knowing where everything is.',
    type: 'enum',
    options: ['me', 'partner', 'joint'],
    allowUnknown: false,
    showIf: (a) => a.has_partner === 'household',
  },
  {
    id: 'partner_knows',
    section: 'A',
    prompt: 'Would your partner know where everything is held if they needed to?',
    rationale: 'Feeds rule 18 on only one of you knowing where everything is.',
    type: 'enum',
    options: [...YES_NO_DK],
    allowUnknown: true,
    showIf: (a) => a.has_partner === 'household',
  },
  {
    id: 'base_currency',
    section: 'B',
    prompt: 'Which currency shall we use?',
    rationale: 'Sets the currency used for everything in the assessment.',
    type: 'currency',
    options: [...CURRENCIES],
    allowUnknown: false,
  },
  {
    id: 'income_monthly',
    section: 'B',
    prompt: 'Roughly how much take-home income does your household get each month?',
    rationale: 'Feeds rule 2 on spending more than you earn.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'spend_housing',
    section: 'B',
    prompt: 'Housing and utilities each month',
    rationale: 'Part of the derived monthly spending figure.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'spend_living',
    section: 'B',
    prompt: 'Day to day: food, transport, leisure, holidays',
    rationale: 'Part of the derived monthly spending figure.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'spend_debt',
    section: 'B',
    prompt: 'Loan and credit card repayments, excluding mortgage',
    rationale: 'Part of the derived monthly spending figure.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'spend_other',
    section: 'B',
    prompt: 'Everything else: insurance, subscriptions, family support',
    rationale: 'Part of the derived monthly spending figure.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'saving_monthly_other',
    section: 'B',
    prompt: 'How much do you save or invest each month outside pensions?',
    rationale: 'Feeds the retirement calculation.',
    type: 'money',
    zeroValid: true,
    allowUnknown: true,
  },
  {
    id: 'cash_total',
    section: 'C',
    prompt: 'Cash in accounts, savings and deposits',
    rationale: 'Feeds the calculation and rules 1 and 15 on your safety net and cash share.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'cash_currency_mismatch',
    section: 'C',
    prompt: 'Is a lot of it in a currency you don\'t spend in?',
    rationale: 'Feeds rule 17 on money and life being in different currencies.',
    type: 'enum',
    options: [...YES_NO_DK],
    allowUnknown: true,
  },
  {
    id: 'money_countries',
    section: 'C',
    prompt: 'Which countries hold your accounts and investments?',
    rationale: 'Gives context on how spread out your money is.',
    type: 'country_list',
    allowUnknown: false,
  },
  {
    id: 'investments_total',
    section: 'C',
    prompt: 'Investments outside pensions: funds, shares, ETFs, savings plans',
    rationale: 'Feeds the retirement calculation.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'fees_known',
    section: 'C',
    prompt: 'Do you know roughly what fees you pay on your investments and pensions?',
    rationale: 'Feeds rule 12 on not knowing what you pay in fees.',
    type: 'enum',
    options: ['yes', 'no', 'not_sure'],
    allowUnknown: false,
  },
  {
    id: 'home_value',
    section: 'C',
    prompt: 'Value of the home you live in',
    helper:
      'The home you live in is not counted towards retirement, because you will still need somewhere to live.',
    rationale: 'Feeds rule 16 only, on most of your wealth being in property.',
    type: 'money',
    zeroValid: true,
    allowUnknown: true,
  },
  {
    id: 'home_mortgage',
    section: 'C',
    prompt: 'Mortgage still owed on it',
    rationale: 'Feeds rule 16 only, on most of your wealth being in property.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'property_value',
    section: 'C',
    prompt: 'Value of any other property you own',
    rationale: 'Feeds the calculation and rule 16 on most of your wealth being in property.',
    type: 'money',
    zeroValid: true,
    allowUnknown: true,
  },
  {
    id: 'property_mortgage',
    section: 'C',
    prompt: 'Mortgage owed on that',
    rationale: 'Feeds the calculation and rule 16 on most of your wealth being in property.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'property_for_retirement',
    section: 'C',
    prompt: 'Do you expect that property equity to help fund your retirement?',
    rationale: 'Feeds the retirement calculation.',
    type: 'enum',
    options: [...YES_NO_DK],
    allowUnknown: true,
  },
  {
    id: 'debt_total',
    section: 'C',
    prompt: 'Non-mortgage debt owed today: loans, cards, car finance',
    rationale: 'Feeds rule 13 on expensive or unmeasured debt.',
    type: 'money',
    zeroValid: true,
    allowUnknown: true,
  },
  {
    id: 'debt_max_rate',
    section: 'C',
    prompt: 'Highest interest rate you pay on it',
    rationale: 'Feeds rule 13 on expensive or unmeasured debt.',
    type: 'percent',
    allowUnknown: true,
  },
  {
    id: 'debt_at_retirement',
    section: 'C',
    prompt: 'Will any significant debt still be owed when you retire? Roughly how much?',
    rationale: 'Feeds the calculation and rule 14 on debt still running in retirement.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'beneficiaries_named',
    section: 'D',
    prompt: 'Have you named who inherits your pensions and life cover?',
    rationale: 'Feeds rule 11 on nobody being named to inherit.',
    type: 'enum',
    options: [...YES_NO_DK],
    allowUnknown: true,
  },
  {
    id: 'life_cover',
    section: 'E',
    prompt: 'Do you have life insurance? If yes, roughly how much cover?',
    rationale: 'Feeds rule 3 on people depending on you with no cover.',
    type: 'enum',
    options: [...YES_NO_DK],
    allowUnknown: true,
  },
  {
    id: 'life_cover_amount',
    section: 'E',
    prompt: 'Do you have life insurance? If yes, roughly how much cover?',
    rationale: 'Feeds rule 3 on people depending on you with no cover.',
    type: 'money',
    allowUnknown: true,
    showIf: (a) => a.life_cover === 'yes',
  },
  {
    id: 'illness_cover',
    section: 'E',
    prompt: 'Do you have critical illness or income protection cover?',
    rationale: 'Feeds rule 4 on having no cover if you cannot work.',
    type: 'enum',
    options: [...YES_NO_DK],
    allowUnknown: true,
  },
  {
    id: 'health_cover',
    section: 'E',
    prompt: 'Do you have health cover where you live, private or public?',
    rationale: 'Feeds rule 5 on no health cover recorded.',
    type: 'enum',
    options: [...YES_NO_DK],
    allowUnknown: true,
  },
  {
    id: 'will',
    section: 'E',
    prompt: 'Do you have a will?',
    rationale: 'Feeds rule 6 on succession arrangements worth reviewing.',
    type: 'enum',
    options: ['yes', 'no'],
    allowUnknown: false,
  },
  {
    id: 'will_country',
    section: 'E',
    prompt: 'Which country\'s law is it under?',
    rationale: 'Feeds rule 6 on succession arrangements worth reviewing.',
    type: 'country',
    allowUnknown: false,
    showIf: (a) => a.will === 'yes',
  },
  {
    id: 'will_year',
    section: 'E',
    prompt: 'When was it last reviewed?',
    rationale: 'Feeds rule 6 on succession arrangements worth reviewing.',
    type: 'year',
    allowUnknown: true,
    showIf: (a) => a.will === 'yes',
  },
  {
    id: 'retire_age',
    section: 'F',
    prompt: 'At what age would you like to retire?',
    rationale: 'Feeds the retirement calculation.',
    type: 'integer',
    allowUnknown: false,
  },
  {
    id: 'retire_country',
    section: 'F',
    prompt: 'Where do you expect to live then?',
    rationale: 'Gives context on where you plan to retire.',
    type: 'country',
    allowUnknown: true,
  },
  {
    id: 'retire_income_monthly',
    section: 'F',
    prompt:
      'In today\'s money, how much take-home income would you want each month in retirement?',
    helper:
      'Think about the lifestyle you want at today\'s prices. We adjust for inflation for you.',
    rationale: 'Feeds the retirement calculation.',
    type: 'money',
    allowUnknown: true,
  },
  {
    id: 'inflation_rate',
    section: 'G',
    prompt: 'Inflation',
    helper: 'Default 3%, range 2% to 5%.',
    rationale: 'Assumption used to restate future money in today\'s terms.',
    type: 'percent',
    allowUnknown: false,
  },
  {
    id: 'investment_growth_rate',
    section: 'G',
    prompt: 'Growth on investments and pensions',
    helper: 'Default 5%, range 3% to 7%.',
    rationale: 'Assumption used to grow investments and pensions to retirement.',
    type: 'percent',
    allowUnknown: false,
  },
  {
    id: 'cash_growth_rate',
    section: 'G',
    prompt: 'Growth on cash',
    helper: 'Default 2%, range 0.1% to 4%.',
    rationale: 'Assumption used to grow cash to retirement.',
    type: 'percent',
    allowUnknown: false,
  },
  {
    id: 'property_growth_rate',
    section: 'G',
    prompt: 'Growth on property',
    helper: 'Default 3%, range 0.1% to 5%.',
    rationale: 'Assumption used to grow property to retirement.',
    type: 'percent',
    allowUnknown: false,
  },
  {
    id: 'withdrawal_rate',
    section: 'G',
    prompt: 'Income your pot is assumed to provide each year',
    helper:
      'Default 4%, range 3% cautious, 4% moderate, 5% higher. This is a planning assumption, never a "safe" rate.',
    rationale: 'Assumption used to turn the pot into yearly retirement income.',
    type: 'percent',
    allowUnknown: false,
  },
  {
    id: 'learning_priorities',
    section: 'H',
    prompt: 'What would you like to understand better?',
    rationale: 'Ranks which blind spots get explained first.',
    type: 'multi_select',
    options: [...TOPICS],
    allowUnknown: false,
  },
];
